### ISSUE TITLE
Import script

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Dutranslator#11]
Pour les merges/import etc si options, j'essaie autant que possible d'éviter les popups et plutôt changer de page dans l'ui principale (comme pour les settings et outils)

Le bouton import vide le tableau d'abord (création d'un nouveau fichier).
Pour ajouter, on va plutot utiliser le bouton "merge" (autre issue)

Import ne crée pas de doublon, il faut faire un check avant de remplir le tableau pour virer les chaines identiques

Tout ce qui est là est réutilisé dans #68 et #67 notamment, on va essayer de bien ranger dans de jolies classes (qui héritent de QThread) :)

Pour tout ce qui est UI, plutot que de coder je suis pour qu'on utilise Designer

- [x] detect all tr() functions

Les fonctions tr("truc à traduire") doivent être détectées, et les chaines correspondantes ajoutées dans le tableau

- [x] Import original jsx: detect strings (option : single or double quotes or both)

les chaînes de caractères non commentées (pas après // dans une ligne, pas dans entre /* et */ en multiligne) doivent être détectées. Avant l'import, afficher un panneau d'options pour demander si on importe les chaines entre guillemets simples ou doubles ou les deux.
(dans duik, je mets les chaines à traduire entre guillemets double, et simple pour les trucs qui ne sont pas à traduire. pratique ;) )
Pour la détection des chaines, une regexp : https://regexr.com/3bf7l
`("|')((?:\\\1|(?:(?!\1).))*)\1`
Attention que Qt veut des chaines de caractères, ce qui est chiant c'esst qu'il faut bien faire gaffe à échapper tous les backslashes du coup
on peut ajouter à la regexp le fait qu'il ne doive jamais y avoir // devant
Pour les commentaires en bloc /* */ moi ce que je fais c'est que je lis le fichier ligne par ligne, si je détecte /* je met un flag sur true et j'attends de trouver un */.

Toutes les chaines détectées sont ajoutées au tableau.

- [ ] Update script with tr() functions option

Option #68 pour ajouter les fonctions tr() manquantes dans le script

**Comment by oktomus** [comment]
Est-ce qu'il y a des fois ou tu appelle tr en passant une variable ?

**Comment by Nico-Duduf** [comment]
Hum... Bonne remarque.
A priori non. D'ailleurs si ça arrivait, ça reviendrait plus ou moins au meme que d'appeler tr à la création de la variable.
Enfin, plutôt moins que plus, ya bien un cas où on est forcé de passer une variable à tr, c'est quand on chope la string ailleurs, genre dans un fichier ou via un socket. Mais bon c'est un cas hyper particulier
et dans un script, ya peu de chances que l'on ait à passer ce cas là à tr

donc si la question est : est ce qu'on s'amuse à aller chercher les string contenues dans les variables passées à tr : pas pour l'instant sauf si pour toi c'est trivial ;)

**Comment by oktomus** [comment]
Ok ! Non ce n'est pas trivial pour moi ^^

**Comment by oktomus** [comment]
- [ ] Vider le tableau avant l'import
- [ ] Gérer les erreurs de parsing
- [ ] Remplir le tableau
