### ISSUE TITLE
Create dutranslator files

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Dutranslator#12]
One-click tool to create the translator jsxinc

**Comment by kevinmasson** [comment]
You mean the files with all the lines which adds translations into js arrays ?

I don't think that creating js file for translation is the way to go, I suggest to use a data representation format like **JSON**. This has many benefits like: 
- We can export the translations as an open format which can be edited only with a texteditor (In my case, I will use vim to translate, no the tool because I write much faster with it.). The point is that it can be useful if you just want to do a minor change and you don't won't to install the app
- We can use the output translations **on ANY code**, we just need to change the getAvailableLangauges. ([the way to go ?](https://www.w3schools.com/Js/js_json_parse.asp)) This is really important because Dutranslator could be use to translate non-js tools like Dutranslator 😃 

JSON could be the default format, but choosing a format would be nice, for example, I think that QT require XML ?

The only problem is that I'm not sure that AE api allows to parse data file. To check.

**Comment by Nico-Duduf** [comment]
You're right. When I developped the translation system for Duik, I didn't plan to make something versatile, the idea came later, but it would be good to use JSON instead of the current javascript file.

I can include a JSON parser in the translator script to make it easy to implement, I used it in other scripts it works well in After Effects.

I'm creating a new issue for this, and I'll take care of it for Duik 16 and v1.0 of DuTranslator.

By the way, on this issue I meant creating the translator script to be included in other scripts, not the translations files.

**Comment by Nico-Duduf** [comment]
As for translating Dutranslator itself, I usually use the Qt Linguist tool which is very powerful and easy to use ; it's not as standard as JSON though.
The idea of implementing our own translation framework using very standard data formats as XML or JSON is not bad, but it would mean that strings used in the UI would have to be added in the source code with our own translation methods, and not via Qt Designer. Why not... I don't know, it's so quick to build UI in designer I'm a bit reluctant when thinking I'll have to add the strings manually in the constructor ;)

**Comment by kevinmasson** [comment]
We can use QT Linguist for qt apps and json for other non-ui-designed tools. But don't forget that some people who could translate the tool don't have Qt on their machine. 
Isn't Qt Linguist using a standard format to store translations ?

**Comment by Nico-Duduf** [comment]
Here is an example of a translation made with Qt Linguist:
When you open a project in Qt Linguist, it creates a .ts file which is an XML like this:
https://github.com/Rainbox-dev/Dufrap/blob/master/src/dufrap_en.ts

The translations are done at runtime with a `tr("original string")` method (which itself calls [`QTranslator::translate("")`](http://doc.qt.io/qt-5/qtranslator.html#translate)), which returns the translated string corresponding to the original string. This method is added by Qt Designer itself when creating the UI.

The bad thing is that it is not this XML which is used at runtime, but a .qm file generated by Linguist, which is non-standard:
https://github.com/Rainbox-dev/Dufrap/blob/master/src/dufrap_en.qm

I'm thinking that what can be done is reimplementing this [`QTranslator::translate("")`](http://doc.qt.io/qt-5/qtranslator.html#translate)) method to use our own JSON translation data files instead of .qm files.

Here's how language is loaded at runtime, before creating the UI, using the [QTranslator](http://doc.qt.io/qt-5/qtranslator.html) class:

```
int main(int argc, char *argv[])
{
 QTranslator translator; //the translation class
    translator.load("path/to/translationFile"); //a way to auto-load the system language if found
    QApplication a(argc, argv);
    a.installTranslator(&translator);
    MainWindow w(argc,argv);
    w.show();
    return a.exec();
}
```

So we could reimplement `QTranslator.load("path")` too, writing our own subclass of QTranslator
I think it should be quite simple.

**Comment by Nico-Duduf** [comment]
I'm creating an issue for this, I think this can be very useful to make our JSON translations work easily for Qt apps too

**Comment by kevinmasson** [comment]
That sounds great ! If somehow we can't reimplement it, we could generate the xml and build the qm file on releases only

**Comment by oktomus** [comment]
We don't need to do it anymore since we use json files ?

**Comment by Nico-Duduf** [comment]
we could just add an option/button somewhere which would output this file
https://github.com/Rainbox-dev/Dutranslator/blob/master/extendscript/Dutranslator.jsxinc
and maybe other files in other languages (like our planned Qt reimplementation of the tr() method)
Just a convenient way to not lose those files and easily distribute them :)

We'd just have to include them in the resource file, and copy them.
I'll do this, assigning myself ;)

**Comment by oktomus** [comment]
Effectively, that could be usefully, I didn't really understood what the issue was about ^^ Thanks
