### ISSUE TITLE
Asynchronous UI

### ISSUE THREAD

**Issue by oktomus** [Rainbox-dev/Dutranslator#20]
Pas mal de chose à modifier dans le code pour que l'UI soit asynchrone et permettre, par exemple, la mise à jour de la progress bar ou l'utilisation de l'UI pendant un calcul. Je sais comment faire, mais ca va prendre un peu de temps. Il faut tout faire fonctionner avec des signaux et slots. Tu es bien parti mais il manque quelques petits détails.

Et aussi, c'est pas très documenté là :P

**Comment by kevinmasson** [comment]
Du coup dis moi si tu veux bien que je fasse des grosses modifs ou pas

**Comment by Nico-Duduf** [comment]
Yes, c'est la voie à suivre, j'ai juste pas pris le temps de le faire parce que je voulais sortir une version test de l'outil en mars, j'ai vraiment fait ça très vite (comme d'hab.... :( )

go on!

**Comment by kevinmasson** [comment]
Pour ce qui est des tableaux, j'avais déjà utilisé ca mais pas en grosse quantité. Je jetterais quand même un oeil.

Pour le model/view, oui je connais, c'est super bien mais ca n'implique pas forcement (voir pas du tout) de meilleur performances, ca facilite l'évolution du code en revanche. 
Ca peut peut être accélérer le process si tu as un model pour plusieurs view, ce qui n'est pas le cas ici.
Je regarderais ça un jour ou l'autre :)

**Comment by Nico-Duduf** [comment]
C'est bien ce que je pensais.
Faudra quand même que je me penche sur comment ça marche, je trouve ça effectivement plus propre et ça peut être vachement utile...
