### ISSUE TITLE
Avoid scroll bars in translations labels

### ISSUE THREAD

**Issue by oktomus** [Rainbox-dev/Dutranslator#27]
Avoid this
![screenshot_2017-03-15_21-36-10](https://cloud.githubusercontent.com/assets/4656466/23971828/6e41ddfe-09c7-11e7-94e1-20d8090fe6a2.png)

**Comment by oktomus** [comment]
Ce sont des widgets non ? Si c'est le cas il faut juste faire un setSizePolicy.

**Comment by Nico-Duduf** [comment]
Je ne crois pas, la taille des widgets est décidée par le tableau lui même, c'est la taille des colonnes/lignes qu'il faut ajuster.
Je sais comment faire (je l'ai dans un autre outil ici, faudrait juste réadapter un peu), c'est juste un peu chiant que ça reste bien ergonomique : la taille idéale pour l'utilisateur dépend du contenu (de la quantité de texte et de lignes de texte) autant que de la taille de la fenêtre elle-même ; évidemment, l'utilisateur peut toujours resizer lui même assez finalement, donc c'est pas primordial...

**Comment by oktomus** [comment]
Ok je te laisse voir ça

**Comment by Nico-Duduf** [comment]
avec le resize automatique des colonnes, il y a beaucoup moins de scroll bars

je ne suis pas pour les enlever toutes, sinon ca peut faire des lignes très hautes, et c'est pas pratique, donc statut quo pour moi

Soit dit en passant : il faudrait surtout revoir dans Duik l'usage de certaines strings ou j'ai usé et abusé des retours à la ligne, qui pourraient être divisées en plusieurs ;)
