### ISSUE TITLE
Create table widgets continuously

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Dutranslator#29]
create widgets continously as soon as the app is launched (with a pause to not freeze UI) to speed up the parsing process.

Need to check how many widgets to create (depending on a translation file of duik for example: just a bit more widgets than needed to load all the file)

**Comment by oktomus** [comment]
And if there isn't enough widget, you could add more during the parsing

**Comment by oktomus** [comment]
It's implemented. But unless the user wait like 10 seconds before opening the file, it's useless process.

**Comment by Nico-Duduf** [comment]
not completely useless, it unfroze the progressbar,
and relaunching the process right after the end of the parsing will enable features like merging another file quickly
And, if the user opens another file after working on the first one, it's far quicker too ;)

**Comment by oktomus** [comment]
Yes that's right :)
