### ISSUE TITLE
Add application icon

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Dutranslator#3]
- [x] Windows
- [x] MacOS
- [ ] Linux

**Comment by Nico-Duduf** [comment]
Not very useful on Linux (as Adobe After Effects is only available on MacOS and Windows), delayed the linux icon to the 1.0 milestone

**Comment by kevinmasson** [comment]
Hey, I use linux all the time :p 
Btw, I changed anything and the icon shows up nicely : 
![screenshot_2017-03-13_21-09-59](https://cloud.githubusercontent.com/assets/4656466/23875457/7289857a-0831-11e7-8572-b40f5e8a0311.png)

**Comment by oktomus** [comment]
So I guess it can be closed ? :)

**Comment by Nico-Duduf** [comment]
yes :)
