### ISSUE TITLE
Can't grab scroll bar when at 0% or 100%

### ISSUE THREAD

**Issue by oktomus** [Rainbox-dev/Dutranslator#30]
When the scroll bar is at the top or at the bottom, i can't grab the knob to scroll, i have to use my mouse wheel or click in the middle of the bar.
See the scroll bar on the right.
![screenshot_2017-03-22_11-59-59](https://cloud.githubusercontent.com/assets/4656466/24196858/396db88e-0ef7-11e7-80fd-849d272b225c.png)
It's a really weird bug, but it can confusing when you want to go through a big list really fast ^^

**Comment by Nico-Duduf** [comment]
Indeed...
That's a mistake in the css, there's an invisible scroll button on top of the bar, I'll fix this!

Le 22 mars 2017 13:02:00 GMT+01:00, Kevin Masson <notifications@github.com> a écrit :
>When the scroll bar is at the top or at the bottom, i can't grab the
>knob to scroll, i have to use my mouse wheel or click in the middle of
>the bar.
>See the scroll bar on the right.
>![screenshot_2017-03-22_11-59-59](https://cloud.githubusercontent.com/assets/4656466/24196858/396db88e-0ef7-11e7-80fd-849d272b225c.png)
>It's a really weird bug, but it can confusing when you want to go
>through a big list really fast ^^
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Rainbox-dev/Dutranslator/issues/30

-- 
Nicolas "Duduf" Dufresne
Réalisateur - Développeur - Formateur
Co-fondateur de Rainbox, coopérative de production audiovisuelle
