### ISSUE TITLE
Update translator.jsxinc to use JSON

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Dutranslator#35]
in particular getAvailableLanguages and maybe other functions

**Comment by oktomus** [comment]
Do you have a js snippet that parse Json ? Or we start from scratch ?

**Comment by Nico-Duduf** [comment]
Yes, I got a free js JSON Parser, which is really great and works well in After Effects, I already use it in some other scripts.
Let me upload a new translation.jsx file in the Tests/UI folder which includes this parser, and you'll be able to re-implement the current translator

**Comment by Nico-Duduf** [comment]
(give me just 5 minutes and it's done ;) )

**Comment by oktomus** [comment]
Great, thanks

**Comment by Nico-Duduf** [comment]
Done, available!

**Comment by Nico-Duduf** [comment]
We should move the dev of the translator here instead of the Duik Repo, this is part of Dutranslator more than Duik now

**Comment by Nico-Duduf** [comment]
I'm doing this right now

**Comment by Nico-Duduf** [comment]
Done, it's here https://github.com/Rainbox-dev/Dutranslator/tree/master/extendscript

**Comment by Nico-Duduf** [comment]
Include changes in #54
