### ISSUE TITLE
Row size issue when adding new rows

### ISSUE THREAD

**Issue by oktomus** [Rainbox-dev/Dutranslator#47]
![screenshot_2017-03-26_16-27-26](https://cloud.githubusercontent.com/assets/4656466/24333065/4d79a390-1241-11e7-8223-af292a830c18.png)
This also occur when the rows are filled.
I tried `adjustRowToContent` but this make the rows huge

**Comment by Nico-Duduf** [comment]
Je n'ai pas le problème sous windows
Je teste sous mac

Mais je vais quand meme changer un petit peu la facon dont les boutons sont ajoutés, en créant un widget avec designer, ca sera plus pratique pour ajouter des boutons par la suite

**Comment by Nico-Duduf** [comment]
pas de souci sous mac non plus

**Comment by Nico-Duduf** [comment]
Done!

A tester sous linux voir si il y a toujours le problème

**Comment by oktomus** [comment]
Nickel sur Linux, tu as fait comment ?

**Comment by Nico-Duduf** [comment]
Simplement en créant une classe cotnenant les deux boutons de la première colonne et en ajoutant ça, plutôt que de le faire directement dans le code de mainwindow.
C'était pas censé régler le problème, mais ça doit contourner un vieux bug de Qt

**Comment by oktomus** [comment]
Magique !
