### ISSUE TITLE
full width columns

### ISSUE THREAD

**Issue by oktomus** [Rainbox-dev/Dutranslator#49]
- Avoid empty space on the right
- Make the translations coulmns larger than others

**Comment by Nico-Duduf** [comment]
this is the same kind of issue than #27

**Comment by oktomus** [comment]
Yes but I don't think we can solve them the same way

**Comment by Nico-Duduf** [comment]
Indeed, this one is simpler, I think we just have to resize the text columns (original and translation) when parsing is finished in `parsingFinished()`

**Comment by Nico-Duduf** [comment]
I'm on it!

**Comment by oktomus** [comment]
That's a good idea to check it in the resize event. But if you do so, don't forget to resize on the init
