### ISSUE TITLE
Replace open buton by a menu

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Dutranslator#51]
menu items:

- open
- merge

**Comment by oktomus** [comment]
QAction don't allow to add sub menus. So we have two solutions:

1. We create a menu on the mouse position when we click on the action, and we map shortcuts to functions instead of actions
2. We don't use QToolBar and QActions but QDockedWidget and QPushButtons instead. 

What do you prefer ?

**Comment by Nico-Duduf** [comment]
if I remember correctly, QMenu can be added in QToolbar ;)
And the QMenu can contain the two QActions

**Comment by oktomus** [comment]
But QMenu can't have any icon ? Not sure about this

**Comment by Nico-Duduf** [comment]
it does ;)
I used it in another app, it works like a qaction when added to a toolbar, except it has a popup menu containing either qaction or other qmenu
http://doc.qt.io/qt-5/qmenu.html

**Comment by oktomus** [comment]
Ok great :)

**Comment by oktomus** [comment]
Hey, I've tried but I didn't get to something similar as other icons. What I've done is on the branch featureUi51, could you take a look at it ?

**Comment by Nico-Duduf** [comment]
Yes!

(mais j'aimerais que ma putain d'appli github desktop arrive à sync les nouvelles branches quand yen a, jcomprend pas ce qu'il faut faire pour les voir apparaitre)

**Comment by oktomus** [comment]
A la mano: `git pull origin --all` je crois via git bash

**Comment by Nico-Duduf** [comment]
I've had a look, I thought it was simple, but it's not really straightforward ;)
I've found how it works in one of my older projects: the menu has to be set on a QAction, and you have to add this QAction to the toolbar....

```
    QMenu * menu = new QMenu(this);
    menu->addAction("test1");
    menu->addAction("test2");
    QAction *bouton = new QAction("bouton");
    bouton->setMenu(menu);
    mainToolBar->addAction(bouton);
```

Also, the QAction containing the Menu HAS to be added to the toolBar AFTER setMenu is called - I had to remove it from the ui file in Qt Designer.

What's nice is that the menu being contained in an QAction means it's a nice open button with a default action and the menu as an option :)
And all actions can be created in Qt Designer, which I like better when working on the icons, I have a quicker preview.

C'est tordu quand même un peu, pas très intuitif la première fois..... Surtout que la doc de QToolbar explique pas que les menu doivent etre dans des actions

Je commit le truc dans quelques minutes, le temps de cleaner

Pour l'appli desktop, en fait la branche apparait au bout de qqs minutes, c'est zarb. Mais ouais, à la mano sinon...

**Comment by Nico-Duduf** [comment]
done, only need to update CSS now. I'll do this ASAP

**Comment by oktomus** [comment]
Transfered this to #65
