### ISSUE TITLE
Faster loading of Dutranslator.jsxinc

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Dutranslator#54]
Parsing all language files is too long, so:

Make including the languageId in the translations filename mandatory, with a filename like:
prefix + languageId + suffix
suffix being ".json" by default.

This way `getAvailable()` only has to read the languageId in the filename and will be a lot faster, and the corresponding file is parsed only when running `setLanguage()`

Will have to be able to set a default language too, which is not included in the translation files: when setting the default language, the original string is returned (only replacing the optionnal arguments)

- [x] Store folder, prefix, suffix and default languageId in a `Dutranslator.settings` object
Dutranslator.settings.folder //(default ".")
Dutranslator.settings.prefix
Dutranslator.settings.suffix //(default ".json")
Dutranslator.settings.originalLanguageId //(default "en" ?)
- [x] Update `getAvailable()` to only read the languageId in the translations filenames
- [x] Implement `setLanguage()` to parse the translation file
- [x] Re-implement `tr(s, context, args)` to return `s` if current languageId is == to default languageId

**Comment by oktomus** [comment]
By the way, how does duik stores the language setted by the user ?

**Comment by oktomus** [comment]
Almost done :)
