### ISSUE TITLE
JS, Add a function which returns the pretty name for a language id

### ISSUE THREAD

**Issue by oktomus** [Rainbox-dev/Dutranslator#55]
Like this, if we want to show available languages to the user, we could use this to display a nice string.
For example, for "en" the function would return "English".

**Comment by oktomus** [comment]
I wait your validation before starting the implementation

**Comment by Nico-Duduf** [comment]
This is a good idea, we can use this:
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
I think the more user friendly (most well known) is using the 639-1 column with two letters only, and the Native name.

Only if the id in the file name is not found, we can parse the file to read the language name.

**Comment by oktomus** [comment]
Ok great !

**Comment by oktomus** [comment]
How should we manage the native names ? Because taking french for exemple, the native name is : _Français, **la langue française**_. And this is it for each languages.

**Comment by Nico-Duduf** [comment]
let's use the first one, the one before the first comma when there are commas (and strip the eventual part in parenthesis)

**Comment by Nico-Duduf** [comment]
if it's not correct and someone use the language, we'll get feedback and fix it ;)

**Comment by oktomus** [comment]
Yeah sure :)

**Comment by oktomus** [comment]
Ok so I don't think that's a greate idea ? Maybe I could just search for "languageName" string in the translation file when loading the availables langauges. It will be fast since the name is at the top. 
What do you think about this @Nico-Duduf ?
The pretty name function is not a great idea I think because we have to write by hand the pretty name of all languages. And if one day we want to add a variant of a language, we won't be able to do it.

**Comment by Nico-Duduf** [comment]
This means at first reading only the first lines of the JSON file without parsing it to retrieve the language name.

The problem I see is that it will work only if the program which generated the json writes the languageName BEFORE the translations, but in JSON specs, the attributes of an object are not ordered, so there's no guarantee to that.

Anyway, we could just add this info in the documentation:
"Warning: the languageName, version, and languageId MUST be at the beginning of the file, before anything else.
This is needed to be able to quickly retrieve those infos without parsing the whole file."

**Comment by oktomus** [comment]
Yes but this made me think of a potential issue, some json compiler order fields by their name. Translations is after languageName but we may have issues in the future.
Why not calling the translation file `translation_code_name` ? Like `tr_duik_fr-FR_Français.json

**Comment by Nico-Duduf** [comment]
Hum... I don't like the idea of including special characters in file names, there already are too many issues when porting apps to MacOS ;)

Another idea: why not rename languageId, languageName and maybe version to "_languageName", "_languageId", and "_version" ?
Or any other leading character which WILL be before anything else?

**Comment by Nico-Duduf** [comment]
anyway, the issue could appear no matter what as the fields are not necessarily orderd...

May be we should change the JSON translation specs to be an Array of two objects: the first one being metadata, and the second one the translations. As Array are ordered, this should fix the issue in any case

**Comment by Nico-Duduf** [comment]
something like:

```
{   "dutranslator": [
        {
            "version": "1.0",
            "languageId": "fr_FR",
            "languageName": "Français",
        },
        {
            "translations": [
                { "source": "first item", "translation": "premier élément", "context": "accueil", "contextId": 1, "comment": "exemple de traduction"},
                { "source": "second item", "translation": "deuxième élément", "context": "accueil", "contextId": 2, "comment": "autre exemple"}
            ]
        }
    ]
}

```

**Comment by Nico-Duduf** [comment]
I really don't know what's best...

**Comment by oktomus** [comment]
That's an idea, still, I think it's better to find a workaround than storing any language name for each language code.. The leading character won't help. The array is a great idea, and people don't see how json is managed so I guess it's not a problem ?

**Comment by Nico-Duduf** [comment]
you're right, let's do this!
