### ISSUE TITLE
Error download list in website

### ISSUE THREAD

**Issue by eZioPan** [Rainbox-dev/Dutranslator#58]
On the Installation section
https://rainboxprod.coop/en/dutranslator-is-available/
3 platform download link seems not in order
![2017-07-01 21 21 36](https://user-images.githubusercontent.com/10928361/27762366-52892b2c-5ea3-11e7-8da9-83d0589a1337.png)

Windows link give Mac program
Mac OS link give Linux program
Linux link give Windows program

Test on Chrome on Windows and Mac, Safari on Mac

**Comment by Nico-Duduf** [comment]
thanks ;)

fixed
