### ISSUE TITLE
Update JSON translation files

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Dutranslator#60]
Store the data in an array, see #55 
Already done in the base example, follow this: https://github.com/Rainbox-dev/Dutranslator/blob/master/examples/translations_example.json

**Comment by Nico-Duduf** [comment]
- [ ] needs to update the save and save as
- [ ] needs to update the jsx translator

**Comment by oktomus** [comment]
Concernant l'import, j'ai vu que le context n'etait pas utilisé mais seulement le contextId etait utilisé. Comment veux tu que je gère ça à l'export ? 
On met le context dans comment ? 
Ou on ajoute une colonne au tableau ?

**Comment by Nico-Duduf** [comment]
ha oui on a zappé ca
Pour moi faut une colonne de plus au tableau, tout à droite, et je propose de foutre le contextId encore plus à droite, vraiment tout au bout

**Comment by oktomus** [comment]
Ok !

**Comment by Nico-Duduf** [comment]
Je me demande si il faut modifier la fonction tr() du traducteur JS pour pouvoir demander une traduction avec au choix le contextId ou le context, ça peut etre pas mal

**Comment by Nico-Duduf** [comment]
je crée une issue pour ça

**Comment by Nico-Duduf** [comment]
c'est là #69 ajoutée dans ta todo ;)

**Comment by oktomus** [comment]
Les specs json ne sont pas les meme entre [https://github.com/Rainbox-dev/Dutranslator/blob/master/examples/translations_example.json](https://github.com/Rainbox-dev/Dutranslator/blob/master/examples/translations_example.json) et [https://github.com/Rainbox-dev/Dutranslator/blob/master/examples/Duik_translations_fr.jsonhttps://github.com/Rainbox-dev/Dutranslator/blob/master/examples/Duik_translations_fr.json](https://github.com/Rainbox-dev/Dutranslator/blob/master/examples/Duik_translations_fr.json).

On a un tableau dans la première et seulement des cléfs dans la deuxieme. Je me base sur la deuxieme qui me parrait plus propre.

**Comment by Nico-Duduf** [comment]
ouaip c'est translations_example.json le bon, j'avais mis à jour que celui là après la discussion #55 où on a décidé de tout mettre dans un array (pour que ce soit dans l'ordre et qu'on puisse récup le language en lisant les premières lignes sans avoir à parser le fichier)

Si t'as la foi, tu peux répercuter sur les autres ^^

**Comment by oktomus** [comment]
Ah ok, je vais fix alors

**Comment by oktomus** [comment]
J'ai fini le save as, j'ai aussi fix des bugs (on avait un ligne sur 2 qui disparaissait à l'import)

**Comment by Nico-Duduf** [comment]
top
je fais un check/test en fin de journée de tes commits
