### ISSUE TITLE
Switch from SQLite to QSettings

### ISSUE THREAD

**Issue by oktomus** [Rainbox-dev/Dutranslator#66]

**Comment by Nico-Duduf** [comment]
I've just discovered the class QSettings, which I used in another project. I was thinking about moving to using this instead of sqlite for the settings, it's much simpler.

**Comment by oktomus** [comment]
Task edited. It's always simpler without a database ^^

**Comment by Nico-Duduf** [comment]
Agreed! ^^
I wish I knew QStettings sooner, it's soooo easy to use....
Stores settings in the registry on Win, in an .ini file on *nux, and on Mac... Don't know, but who cares? 😄

**Comment by Nico-Duduf** [comment]
Marche à suivre que j'ai implémentée là : https://github.com/Rainbox-dev/DuFFMpeg/

Je définis APPVERSION dans le .pro

`DEFINES += APPVERSION=\\\"0.0.0-Beta\\\"` (jte laisse voir le numéro à mettre je sais plus où on en est ^^)

Dans main.cpp

    QCoreApplication::setOrganizationName("Rainbox");
    QCoreApplication::setOrganizationDomain("rainboxprod.coop");
    QCoreApplication::setApplicationName("DuTranslator");
    QCoreApplication::setApplicationVersion(APPVERSION);

Et ensuite chaque fois qu'il y a besoin et juste là où il ya besoin d'un settings, ya plus qu'à
`QSettings settings;`
Et ensuite on a tout dans `settings` automatiquement parce qu'on a défini les détails de l'appli dans le main, c'est totomatique et bien cool.
Jte laisse voir la doc de QSettings, c'est tout con.
Ce qui est cool, c'est qu'on a pas besoin de se passer un objet d'une classe à l'autre du coup, ni même besoin d'une classe à part pour les gérer tout est fait là dedans.
