### ISSUE TITLE
Merge file

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Dutranslator#67]
Pour les merges/import etc si options, j'essaie autant que possible d'éviter les popups et plutôt changer de page dans l'ui principale (comme pour les settings et outils)

Fusionne un fichier avec celui ouvert

- [x] Option for file type

Panneau d'options avant de merger : préciser si on fusionne un fichier de traduction (json) ou on importe un fichier de script (jsx, ou autre).
Dans ce deuxième cas, se référer aussi à #11 (et afficher les options correspondantes sur le panneau aussi)

- [x] Option for duplicates

Panneau d'options avant de merger : que faire des duplicatas, les ignorer ou les ajouter
Si ajout, ajouter un nouveau contexte

- [x] when merging, highlight the new strings, add "new" comment

Changer la couleur de fond de la case commentaire par exemple, et ajouter le commentaire "NEW"
D'ailleurs ce qui pourrait etre pratique, c'est même de faire une méthode qui change la couleur de fond de la case commentaire à la détection de certains mots-clefs : NEW, WIP, TODO, OK (orange, jaune, bleu, vert) par exemple ! ou juste la couleur du texte ? à voir

**Comment by oktomus** [comment]
J'ai préparé le terrain pour WIP TODO ... Il suffit juste d'ajouter la couleur qu'on veut dans commentLineEdit.cpp
