### ISSUE TITLE
Stylesheet won't open on linux

### ISSUE THREAD

**Issue by kevinmasson** [Rainbox-dev/Dutranslator#8]
Output : ```QIODevice::read (QFile, "style.css"): device not open```

**Comment by kevinmasson** [comment]
Can be fix using `QFile cssFile("../needed/style.css");`.
I suggest to organize the repo like this : 
```
root
-- .pro file
-- src/
-------- cpp and h files
-- ressources/
-------- icons/
---------------- images files
-------- styles/
---------------- css files
```
But that's just because I'm crazy about organization xD

**Comment by Nico-Duduf** [comment]
yes, that's useful ;)
It's never bad to be a bit too organized ^^

You can do this this week, I'm not working on it these days!

**Comment by kevinmasson** [comment]
Ok great :)

**Comment by kevinmasson** [comment]
Works fine now
